services:
  app:
    hostname: example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8760:80 # CiviCRM will be available on port 8760.
    restart: unless-stopped
    volumes:
      - ./init.sh:/init.sh
      - private:/var/www/html/private
      - public:/var/www/html/public
      - ./ext:/var/www/html/ext
    command: [ "bash", "/init.sh" ]
    environment:
      CIVICRM_DB_HOST: db
      CIVICRM_DB_PORT: 3306
      CIVICRM_DB_NAME: civicrm
      CIVICRM_DB_USER: civicrm
      CIVICRM_DB_PASSWORD: ${MYSQL_PASSWORD}
      # CIVICRM_DSN: mysql://civicrm:${MYSQL_PASSWORD}@db:3306/civicrm # Note: you can also pass database credentials as a DSN.
      CIVICRM_UF_BASEURL: http://localhost:8760
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    hostname: db
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: civicrm
      MYSQL_USER: civicrm
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  private:
  public:
  db:
